version: '3.9'
services:
  web:
    command: "python3 app.py"
    expose: 
      - 5030
    image: aikezz/st124196_a2:latest
    container_name: st124196_aike
    
    platform: linux/x86_64
    environment:
      - HOST=0.0.0.0
      - PORT=5030
    
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service

      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st124196.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is web-st123783
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124196.rule=Host(`st124196.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st124196.tls=true
      - traefik.http.routers.web-st124196.tls.certresolver=production
      - traefik.http.routers.web-st124196.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true


# services:
#   dev:
#     build: .
#     command: "python3 app.py"
#     image: st124196_a2
#     environment:
#       - HOST=0.0.0.0
#       - PORT=5000
#     labels:
#       - traefik.enable=true
#       - traefik.http.services.web-st124196.loadbalancer.server.port=5000
#       - traefik.http.routers.web-st124196.rule=Host(`st124196.ml.brain.cs.ait.ac.th`)
#       - traefik.http.routers.web-st124196.tls=true
#       - traefik.http.routers.web-st124196.tls.certresolver=production
#       - traefik.http.routers.web-st124196.entrypoints=websecure
#     networks:
#       - default
#       - traefik_default

# networks:
#   default:
#   traefik_default:
#     external: true
 